name: stylish
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  english_words: ^4.0.0
  provider: ^6.0.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  dio: ^4.0.0
  go_router: ^6.5.7
  google_maps_flutter: ^2.2.6
  google_maps_flutter_web: ^0.4.0+8
  http: ^0.13.6
  json_serializable: ^6.6.2
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  permission_handler: ^10.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/bar_image.png
    - assets/header_image.jpg
    - assets/locations.json



